'use client';
import {useEffect,useState} from 'react';
import type {Filters,Party} from '@/lib/search';
import {apiAvailable,apiBaseUrl} from '@/lib/api';
const api=apiBaseUrl;
const providers=[['tourvisor','Tourvisor'],['aviacenter','AviaCenter'],['hotelbeds','Hotelbeds / HBX'],['ratehawk','RateHawk'],['webbeds','WebBeds'],['tbo','TBO'],['dida','DidaTravel'],['travelgate','Travelgate HotelX'],['expedia','Expedia Rapid'],['duffel','Duffel'],['amadeus','Amadeus'],['samo','SAMO'],['juniper','Juniper'],['traveltek','Traveltek'],['peakwork','Peakwork']];
type Result={provider:string;name:string;fallback:boolean;access_status:string;upstream_access_status?:string;note:string;query:{check_in:string;check_out:string;adults:number;children:number[]};offers:{id:string;kind:string;price:{original_amount:string;original_currency:string};hotel?:{name:string};room?:string;meal?:string;provenance:{access_status:string;pricing_reality:string;bookable:boolean}}[]};
export default function ProviderSearch({filters,party,trigger}:{filters:Filters;party:Party;trigger:number}){
 const [selected,setSelected]=useState(['travelgate']),[network,setNetwork]=useState(true),[samples,setSamples]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[results,setResults]=useState<Result[]>([]);
 const [origin,setOrigin]=useState('LHR'),[destination,setDestination]=useState('JFK'),[codes,setCodes]=useState(''),[departure,setDeparture]=useState(''),[country,setCountry]=useState('');
 async function run(){
  if(busy)return;setError('');setResults([]);
  if(!apiAvailable){setError('API не подключён к этой публикации. GitHub Pages не выполняет серверные проверки поставщиков.');return;}
  if(party.split){setError('Для теста API выберите одинаковую дату возвращения. Split-family уже работает в модели поездки; тест поставщика проверяет один номер с постоянным составом.');return;}
  if(!selected.length){setError('Выберите поставщика.');return;}
  setBusy(true);
  try{const r=await fetch(api+'/api/validation/search',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(180000),body:JSON.stringify({providers:selected,check_in:String(filters.earliest),nights:Number(filters.minNights),date_samples:samples,adults:party.adults,children:party.children,network,flight_origin:origin,flight_destination:destination,hotelbeds_codes:codes?codes.split(',').map(x=>Number(x.trim())):[],tourvisor_departure:departure?Number(departure):null,tourvisor_country:country?Number(country):null})});if(!r.ok){const body=await r.json();throw new Error(typeof body.detail==='string'?body.detail:'Проверьте даты, возраст детей и коды поставщика.')}const body=await r.json();setResults(body.results);}catch(e){setError(e instanceof Error?e.message:'Поиск недоступен')}finally{setBusy(false)}
 }
 useEffect(()=>{if(trigger>0)void run();},[trigger]); // Main search button explicitly triggers a new snapshot.
 return <section className="provider-validation" aria-label="Тестирование API"><h3>ZERO-COST · поиск через API</h3>{!apiAvailable&&<p role="status">Серверный API не подключён к GitHub Pages; тесты поставщиков недоступны.</p>}<p>Даты и состав семьи берём из формы. Проверяем один номер на минимальное число ночей; до трёх последовательных дат. Это отдельные компоненты, а не полная поездка.</p><p className="muted">Travelgate ищет фиксированные тестовые отели ES284122 и BR1518, RateHawk — тестовый регион 6053839. Они не подтверждают выбранное направление, визу или экономию.</p>
  <div className="provider-choices">{providers.map(([id,name])=><label className="check-field" key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(e.target.checked?[...selected,id]:selected.filter(p=>p!==id))}/>{name}</label>)}</div>
  <div className="two-fields"><label className="field"><span>Сколько дат проверить</span><select value={samples} onChange={e=>setSamples(Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={network} onChange={e=>setNetwork(e.target.checked)}/>Разрешённые demo / sandbox / trial запросы</label></div>
  {selected.includes('duffel')&&<div className="two-fields"><label className="field"><span>Duffel Test: откуда (IATA)</span><input value={origin} maxLength={3} onChange={e=>setOrigin(e.target.value.toUpperCase())}/></label><label className="field"><span>Duffel Test: куда (IATA)</span><input value={destination} maxLength={3} onChange={e=>setDestination(e.target.value.toUpperCase())}/></label></div>}
  {selected.includes('hotelbeds')&&<label className="field"><span>Hotelbeds: Evaluation hotel codes через запятую</span><input value={codes} onChange={e=>setCodes(e.target.value)} placeholder="Коды из вашего Evaluation content"/></label>}
  {selected.includes('tourvisor')&&<div className="two-fields"><label className="field"><span>Tourvisor: departureId</span><input type="number" min="1" value={departure} onChange={e=>setDeparture(e.target.value)}/></label><label className="field"><span>Tourvisor: countryId</span><input type="number" min="1" value={country} onChange={e=>setCountry(e.target.value)}/></label></div>}
  <p className="muted">Личные тестовые ключи настраиваются на сервере. При недоступном API карточка явно показывает локальный MOCK; цены разных сред не сравниваются.</p><button className="search-button" disabled={busy||!apiAvailable} onClick={run}>{busy?'Проверяем API…':'Проверить выбранные API'}</button>
  {error&&<p role="alert">{error}</p>}
  <div aria-live="polite">{results.map((r,i)=><article className="validation-result" key={r.provider+i}><h4>{r.name} · {r.access_status}</h4><p>{r.query.check_in} → {r.query.check_out} · {r.query.adults} взр. · дети: {r.query.children.join(', ')||'нет'}</p><p className="muted">{r.fallback?'Локальная модель — API не вернул эти цены. ':''}{r.upstream_access_status} {r.note}</p><p>Получено: {r.offers.length}. Показано: {Math.min(4,r.offers.length)}. Для экономического сравнения: 0.</p>{r.offers.slice(0,4).map(o=><div className="validation-price" key={o.id}><span>{o.hotel?.name||o.kind} {o.room||''}</span><strong>{Number(o.price.original_amount).toLocaleString('ru-RU')} {o.price.original_currency}</strong><small>{o.provenance.access_status} · {o.provenance.pricing_reality} · bookable: false</small></div>)}</article>)}</div>
 </section>;
}
