'use client';
import {useEffect,useState} from 'react';
import {money,type Offer,type Party,type Filters} from '@/lib/search';
import {aviasalesLink,bookingLink,datesError,destinationAirports,flightGroups,kupibiletLink,ostrovokLink,type SearchGroup} from '@/lib/purchase-links';
import {quoteIncluded,tripStorageKey,type TripCalculation,type Quote,type QuoteRow} from '@/lib/trip-quotes';
import TripCostSummary from './TripCostSummary';
import {packageRequest} from '@/lib/package-request';
import QuoteEntry from './QuoteEntry';

type Room={group:number;adults:number;ages:string};
const key=(v:unknown)=>JSON.stringify(v);
function parsedAges(s:string){return s.trim()?s.split(',').map(x=>Number(x.trim())):[];}
function roomsFor(groups:SearchGroup[],count:number):Room[]{
 const rooms:Room[]=[];
 groups.forEach((g,i)=>{const n=groups.length===1?Math.max(1,Math.min(count,g.adults)):1;for(let j=0;j<n;j++){rooms.push({group:i,adults:Math.floor(g.adults/n)+(j<g.adults%n?1:0),ages:g.children.filter((_,k)=>k%n===j).join(', ')});}});return rooms;
}
function SearchLink({url,name}:{url:string;name:string}){return <a className="prepared-link" href={url} target="_blank" rel="noopener noreferrer">{name} — результаты поиска ↗</a>;}
function downloadRequest(request:unknown,index:number){const url=URL.createObjectURL(new Blob([JSON.stringify(request,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`package-search-room-${index+1}.json`;a.click();URL.revokeObjectURL(url);}

export default function PurchaseDetails({offer,party,filters,onCalculation}:{offer:Offer;party:Party;filters:Filters;onCalculation?:(c:TripCalculation)=>void}){
 const searchParty=offer.searchParty||party;
 const [groups,setGroups]=useState(()=>flightGroups(searchParty,offer.returns));
 const [out,setOut]=useState(offer.departure),[from,setFrom]=useState(offer.gateway?offer.startAirport:offer.route[0]),[to,setTo]=useState(destinationAirports[offer.code]||'');
 const [positionOut,setPositionOut]=useState(offer.departure),[positionBack,setPositionBack]=useState(()=>groups.map(g=>g.back));
 const [rooms,setRooms]=useState(()=>roomsFor(groups,Number(offer.searchRooms||filters.rooms)));
 const [quotes,setQuotes]=useState<Record<string,Quote>>({}),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState('');
 const pack=['russian','foreign','gatewayPackage'].includes(offer.kind);
 const storageKey=tripStorageKey(offer,party,filters);
 const context=key({country:offer.code,place:offer.resort,out,from,to,groups,rooms,positionOut,positionBack,meal:offer.meal});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.context){const c=JSON.parse(saved.context);if(c.country===offer.code&&c.place===offer.resort&&typeof c.out==='string'&&typeof c.from==='string'&&typeof c.to==='string'&&typeof c.positionOut==='string'&&Array.isArray(c.groups)&&c.groups.length&&c.groups.every((g:SearchGroup)=>typeof g.name==='string'&&Number.isInteger(g.adults)&&g.adults>0&&Array.isArray(g.children)&&g.children.every(Number.isInteger)&&typeof g.back==='string')&&Array.isArray(c.rooms)&&c.rooms.every((r:Room)=>Number.isInteger(r.group)&&r.group>=0&&r.group<c.groups.length&&typeof r.ages==='string'&&typeof r.adults==='number')&&Array.isArray(c.positionBack)&&c.positionBack.length===c.groups.length&&c.positionBack.every((s:unknown)=>typeof s==='string')){setOut(c.out);setFrom(c.from);setTo(c.to);setGroups(c.groups);setRooms(c.rooms);setPositionOut(c.positionOut);setPositionBack(c.positionBack);setQuotes(saved.quotes&&typeof saved.quotes==='object'?saved.quotes:{});}}}catch{setStorageError('Сохранённый расчёт не удалось загрузить.');}setLoaded(true);},[storageKey,offer.code,offer.resort]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(storageKey,JSON.stringify({context,quotes}));}catch{setStorageError('Расчёт не сохранён: хранилище браузера недоступно.');}},[loaded,storageKey,context,quotes]);
 const rows:QuoteRow[]=[];
 const row=(id:string,label:string,params:unknown)=>{const r={id,label,queryKey:key(params)};rows.push(r);return r;};
 const flights=pack?[]:groups.map((g,i)=>row('flight-'+i,'Перелёт туда и обратно · '+g.name,{type:'flight',out,back:g.back,from,to,adults:g.adults,children:g.children}));
 const packages=pack?rooms.map((r,i)=>row('package-'+i,'Полный пакет · номер '+(i+1)+' · '+groups[r.group].name,{type:'package',...packageRequest({kind:offer.kind,from,to,country:offer.code,resort:offer.resort,out,back:groups[r.group].back,adults:r.adults,children:parsedAges(r.ages),meal:offer.meal,stars:offer.stars,rating:offer.rating,operatorCountry:offer.kind==='russian'?'RU':offer.gatewayCountry})})):[];
 const lodging=pack?[]:rooms.map((r,i)=>row('hotel-'+i,'Проживание · номер '+(i+1),{place:offer.resort,out,back:groups[r.group]?.back,adults:r.adults,ages:parsedAges(r.ages),meal:offer.meal}));
 const positioning=offer.gateway?groups.map((g,i)=>row('position-'+i,'До gateway и обратно · '+g.name,{type:'positioning',from:offer.route[0],to:from,out:positionOut,back:positionBack[i],adults:g.adults,children:g.children})):[];
 const extra=offer.costs.filter(c=>!c.label.includes('Пакет')&&!c.label.includes('Перел')&&!c.label.includes('Проживание')).map((c,i)=>row('extra-'+i,c.label,{label:c.label,context}));
 const roomError=groups.some((g,i)=>{const rs=rooms.filter(r=>r.group===i),ages=rs.flatMap(r=>parsedAges(r.ages));return rs.length===0||rs.some(r=>r.adults<1||!Number.isInteger(r.adults)||parsedAges(r.ages).some(a=>!Number.isInteger(a)||a<0||a>17))||rs.reduce((a,r)=>a+r.adults,0)!==g.adults||key(ages.sort((a,b)=>a-b))!==key([...g.children].sort((a,b)=>a-b));});
 const dateError=groups.some(g=>datesError(out,g.back,true))||!!offer.gateway&&groups.some((g,i)=>datesError(positionOut,positionBack[i],true)||positionOut>out||positionBack[i]<g.back);
 const routeError=!/^[A-Z]{3}$/.test(from)||!/^[A-Z]{3}$/.test(to)||from===to;
 const calculation:TripCalculation={offerKey:storageKey,rows,quotes,parametersValid:!roomError&&!dateError&&!routeError,departure:out,returns:groups.map(g=>g.back),from,to};
 const encodedCalculation=key(calculation);
 useEffect(()=>{if(loaded){try{localStorage.setItem(storageKey+':calculation',encodedCalculation);}catch{}onCalculation?.(JSON.parse(encodedCalculation));}},[loaded,storageKey,encodedCalculation,onCalculation]);
 const entry=(r:QuoteRow,isPackage=false)=>{const p=JSON.parse(r.queryKey),searchUrl=['flight','positioning'].includes(p.type)?aviasalesLink(p.from,p.to,p.out,p.back,p.adults,p.children).url:undefined;return <QuoteEntry searchUrl={searchUrl} key={r.id+'-'+r.queryKey} label={r.label} queryKey={r.queryKey} isPackage={isPackage} value={quoteIncluded(quotes[r.id],r.queryKey)?quotes[r.id]:undefined} onSave={q=>setQuotes(old=>{const next={...old};if(q)next[r.id]=q;else delete next[r.id];return next;})}/>;};
 return <section className="purchase-details"><h3>Поиск и стоимость по выбранным предложениям</h3>
 <p>1. Откройте результаты по параметрам ниже. 2. Выберите тариф, номер или полный тур. 3. Внесите полную цену и ссылку — она попадёт в расчёт.</p>
 <TripCostSummary calculation={calculation}/><p className="hint">Поисковая ссылка открывает внешний сайт. Передача цены обратно через ссылку не происходит. Запишите найденную цену ниже: она обновит этот расчёт и карточку. Для постоянной автоматической выдачи нужен разрешённый Search API.</p><details><summary>Учебная модель · SYNTHETIC — {money(offer.price)}</summary><p>Это пример формулы, не цены продавцов. В основной расчёт эти суммы не входят.</p><div className="cost-table">{offer.costs.map(c=><div key={c.label}><span>{c.label}</span><strong>{money(c.amount)}</strong></div>)}<div className="total"><span>Синтетический итог</span><strong>{money(offer.price)}</strong></div></div></details>
 <div className="purchase-query"><label>Аэропорт отправления (IATA)<input value={from} maxLength={3} onChange={e=>setFrom(e.target.value.toUpperCase())}/></label><label>Аэропорт назначения (IATA)<input value={to} maxLength={3} onChange={e=>setTo(e.target.value.toUpperCase())}/></label><label>Общий вылет / заезд<input type="date" value={out} onInput={e=>setOut(e.currentTarget.value)}/></label></div>
 <p className="hint">Аэропорт предложен для поиска, трансфер до {offer.resort} не подтверждён. Изменение параметров исключает прежнюю цену из расчёта. Поля используются для всех ссылок ниже.</p>
 {groups.map((g,i)=>{const result=aviasalesLink(from,to,out,g.back,g.adults,g.children);return <article className="purchase-flight" key={i}><h4>{pack?"Даты пакета · "+g.name:flights[i].label}</h4><p>{from} → {to} · {g.adults} взрослых · дети: {g.children.join(', ')||'нет'}</p><label>Возвращение / выезд · {g.name}<input type="date" value={g.back} onInput={e=>{const value=e.currentTarget.value;setGroups(old=>old.map((x,j)=>j===i?{...x,back:value}:x));}}/></label>
 {!pack&&<>{result.error?<p role="alert">{result.error}</p>:<><SearchLink name="Aviasales" url={result.url!}/>{kupibiletLink(from,to,out,g.back,g.adults,g.children)&&<SearchLink name="Купибилет" url={kupibiletLink(from,to,out,g.back,g.adults,g.children)!}/>}<p className="hint">Маршрут, обе даты и число пассажиров переданы. Купибилет получает также возраст детей. Aviasales возраст не передаёт: проверьте детей и багаж на сайте продавца перед применением цены.</p><details><summary>Если выдача не загрузилась</summary><a href={result.formUrl} target="_blank" rel="noopener noreferrer">Открыть заполненную форму Aviasales</a><p>Дождитесь загрузки формы и нажмите «Найти билеты».</p></details></>}
{entry(flights[i])}</>}</article>;})}
 {offer.gateway&&<><h4>Позиционирование через {from}</h4><p>Запас по модели: {offer.buffer} часов. Установите даты перелётов до gateway с учётом времени рейса и ночёвок.</p><label>Вылет до gateway<input type="date" value={positionOut} onInput={e=>setPositionOut(e.currentTarget.value)}/></label>{groups.map((g,i)=>{const link=aviasalesLink(offer.route[0],from,positionOut,positionBack[i],g.adults,g.children),kb=kupibiletLink(offer.route[0],from,positionOut,positionBack[i],g.adults,g.children);return <article key={i}><label>Обратно из gateway · {g.name}<input type="date" value={positionBack[i]} onInput={e=>{const value=e.currentTarget.value;setPositionBack(old=>old.map((s,j)=>j===i?value:s));}}/></label>{link.url?<SearchLink url={link.url} name="Aviasales"/>:<p role="alert">{link.error}</p>}{kb&&<SearchLink url={kb} name="Купибилет"/>}{entry(positioning[i])}</article>;})}</>}
 {pack&&<><h4>Пакетные туры · {offer.kind==='russian'?'российские операторы':'зарубежные операторы'}</h4><p>Полный тур: перелёт туда/обратно + отель + выбранное питание. {offer.kind==='russian'?'Запрос для российских продавцов и туроператоров.':'Пакет начинается в '+from+'; дорога из '+offer.route[0]+' до этого аэропорта и обратно считается отдельно.'}</p><p>Автоматический поиск туров по точным параметрам ещё не подключён. Ниже подготовлен запрос для каждого номера и ввод цены выбранного тура. Демо-название оператора не является продавцом реального предложения.</p><details><summary>Источники пакетных туров и доступ</summary><p>Российские: Tourvisor — нужен официальный trial-token и справочники; Level.Travel — официальный партнёрский API; Travelata, Onlinetours, Coral Travel, ANEX, PEGAS, FUN&amp;SUN — переход с полным запросом ещё не проверен.</p><p>Зарубежные: TUI / airtours, DERTOUR, Emirates Holidays, Turkish Airlines Holidays — точный поиск из выбранного gateway и условия продажи туристам требуют проверки у продавца. Цена зарубежного тура учитывается только по выбранному предложению.</p><p>Туроператор, страна оператора, размещение, питание и включённые услуги фиксируются с реальной ценой. До подключения источника ни цены, ни наличие мест от него не заявляются.</p></details></>}
 <section><h4>{pack?'Размещение и запросы пакетных туров':'Проживание'} · {offer.resort}</h4><p>Поиск отдельно на каждый номер, с возрастами детей и всеми ночами. Для разных сроков возвращения — отдельный тур на группу. Питание {offer.meal}, звёздность и пляж проверьте в выбранном отеле.</p>{roomError&&<p role="alert">Распределите всех взрослых и каждого ребёнка по номерам ровно один раз.</p>}{rooms.map((r,i)=>{const g=groups[r.group],ages=parsedAges(r.ages),error=datesError(out,g.back,true),os=ostrovokLink(offer.resort,out,g.back,r.adults,ages);return <article className="purchase-flight" key={i}><h4>Номер {i+1} · {g.name}</h4><div className="purchase-query"><label>Группа номера<select value={r.group} onChange={e=>{const v=Number(e.target.value);setRooms(old=>old.map((x,j)=>i===j?{...x,group:v}:x));}}>{groups.map((gr,j)=><option key={j} value={j}>{gr.name}</option>)}</select></label><label>Взрослых в номере<input type="number" min="1" value={r.adults} onChange={e=>{const v=Number(e.target.value);setRooms(old=>old.map((x,j)=>i===j?{...x,adults:v}:x));}}/></label><label>Возраст детей через запятую<input value={r.ages} onChange={e=>{const v=e.target.value;setRooms(old=>old.map((x,j)=>i===j?{...x,ages:v}:x));}}/></label></div><p>{out} — {g.back} · 1 номер</p>{pack?<><p>Вылет из {from}; страна {offer.country}; курорт {offer.resort}; {Math.round((Date.parse(g.back)-Date.parse(out))/86400000)} ночей; питание {offer.meal}; от {offer.stars}★. Даты без отклонений.</p><button type="button" disabled={!!error||roomError||routeError} onClick={()=>downloadRequest(JSON.parse(packages[i].queryKey),i)}>Скачать параметры поиска тура</button>{entry(packages[i],true)}</>:<>{!error&&!roomError?<div className="purchase-site-links"><SearchLink name="Booking.com" url={bookingLink(offer.resort+', '+offer.country,out,g.back,r.adults,ages,1)}/>{os?<SearchLink name="Островок" url={os}/>:<span>Островок: курорт ещё не сопоставлен</span>}</div>:<p role="alert">{error||'Исправьте распределение гостей.'}</p>}{entry(lodging[i])}</>}</article>;})}<button type="button" onClick={()=>setRooms(old=>[...old,{group:0,adults:1,ages:''}])}>Добавить номер</button>{rooms.length>groups.length&&<button type="button" onClick={()=>setRooms(old=>old.slice(0,-1))}>Убрать последний номер</button>}</section>
 <details><summary>Статус остальных сервисов</summary><p>Купибилет: публичная поисковая ссылка с датами и возрастом детей проверена; цена автоматически не передаётся обратно. Туту, сайты авиакомпаний, Яндекс Путешествия, Level.Travel, Travelata и Onlinetours: точные ссылки с полным запросом требуют отдельной проверки / интеграции. Ссылку на найденное предложение можно внести вместе с ценой.</p></details>
 <h4>Остальные расходы</h4><p className="hint">Не учитывайте одно и то же дважды. Если услуга включена в выбранный тариф/пакет, внесите 0 со ссылкой на тариф и описанием. Не оставляйте неизвестный расход нулём.</p>{extra.map(r=><article key={r.id}><b>{r.label}</b>{entry(r)}</article>)}
 {storageError&&<p role="alert">{storageError}</p>}<p className="hint">Расчёт и ссылки сохраняются в этом браузере. Наблюдаемый минимум — LIMITED_REAL; проверенный вами тариф — REAL. Доступность и возможность покупки не подтверждены API.</p>
 </section>;
}
