'use client';
import {useState} from 'react';
import {money} from '@/lib/search';
import {safeSourceUrl,observationValid,type Quote,type PackageEvidence} from '@/lib/trip-quotes';
export default function QuoteEntry({label,queryKey,value,onSave,isPackage=false,searchUrl}:{label:string;queryKey:string;value?:Quote;onSave:(q:Quote|undefined)=>void;isPackage?:boolean;searchUrl?:string}){
 const [amount,setAmount]=useState(value?String(value.amount):''),[url,setUrl]=useState(value?.sourceUrl||''),[description,setDescription]=useState(value?.description||''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState('');
 const [pack,setPack]=useState<PackageEvidence>(value?.packageEvidence||{operatorName:'',operatorCountry:'',hotel:'',room:'',meal:'',includesFlightHotel:false,purchaseConditionsChecked:false});
 return <details className="quote-entry"><summary>{value?`${value.confirmed?'Учтено':'Наблюдалось'}: ${money(value.amount)} · изменить`:'Внести найденную цену в расчёт'}</summary>
 <p className="hint">Полная сумма в RUB за всех указанных пассажиров / за весь срок проживания. Для сборов: сумма за всю поездку; 0 допустим, если услуга включена. Это введённая вами цена, без автоматического подтверждения API.</p>
 <div className="purchase-query"><label>Полная цена, ₽ · {label}<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Ссылка на выбранный вариант<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Что выбрано / что включено<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Рейс и багаж / отель и номер / услуга включена в пакет"/></label></div>
 {isPackage&&<><div className="purchase-query">{([['operatorName','Фактический туроператор'],['operatorCountry','Страна туроператора'],['hotel','Отель выбранного тура'],['room','Тип номера'],['meal','Питание выбранного тура']] as const).map(([field,title])=><label key={field}>{title}<input value={pack[field]} onChange={e=>{const v=e.target.value;setPack(old=>({...old,[field]:v}));}}/></label>)}</div><label className="check-field"><input type="checkbox" checked={pack.includesFlightHotel} onChange={e=>{const v=e.target.checked;setPack(old=>({...old,includesFlightHotel:v}));}}/>Цена включает перелёт туда/обратно и проживание за весь срок для гостей этого номера</label><label className="check-field"><input type="checkbox" checked={pack.purchaseConditionsChecked} onChange={e=>{const v=e.target.checked;setPack(old=>({...old,purchaseConditionsChecked:v}));}}/>Проверены продажа туристам с нашим гражданством, способ оплаты и обязательные доплаты</label><p className="hint">Для зарубежной цены внесите фактическую полную стоимость в рублях; исходную валюту, курс и комиссии укажите в описании. Доплаты, не включённые в пакет, внесите отдельными строками.</p></>}
 {searchUrl&&<><p className="hint">Можно записать цену открытой выдачи Aviasales или Купибилета как наблюдение: она обновит строку перелёта и сумму найденных расходов на 12 часов, но не станет подтверждённым тарифом. Ссылка должна совпадать с маршрутом, датами и числом пассажиров; Купибилет также передаёт возраст детей.</p><button type="button" onClick={()=>{const q:Quote={amount:Number(amount),sourceUrl:url,description,observedAt:new Date().toISOString(),confirmed:false,access_status:'DEEPLINK',pricing_reality:'LIMITED_REAL',bookable:'unknown',evidence:'PUBLIC_PAGE_OBSERVED',queryKey,currency:'RUB'};if(!amount.trim()||!observationValid(q,queryKey)){setError('Укажите положительную сумму в RUB, описание и ссылку на точную выдачу Aviasales или Купибилета.');return;}onSave(q);setError('');}}>Записать наблюдаемую цену</button><button type="button" onClick={()=>setUrl(searchUrl)}>Подставить ссылку этого поиска</button></>}
 <label className="check-field"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Проверены даты, состав, возраст детей, багаж, аэропорты, пересадки и итоговая цена; это реальное предложение, не демо</label>
 <button type="button" onClick={()=>{if(!amount.trim()||!Number.isFinite(Number(amount))||Number(amount)<0||!safeSourceUrl(url)||!description.trim()||!confirmed){setError('Нужны неотрицательная сумма, HTTPS-ссылка, описание и подтверждение параметров.');return;}if(isPackage&&(Number(amount)<=0||![pack.operatorName,pack.operatorCountry,pack.hotel,pack.room,pack.meal].every(s=>s.trim())||!pack.includesFlightHotel||!pack.purchaseConditionsChecked)){setError('Для тура укажите оператора, его страну, отель, номер и питание; подтвердите полный пакет и условия покупки.');return;}onSave({amount:Number(amount),sourceUrl:url,description,observedAt:new Date().toISOString(),confirmed:true,access_status:'DEEPLINK',pricing_reality:'REAL',bookable:'unknown',evidence:'USER_REPORTED',currency:'RUB',queryKey,...(isPackage?{packageEvidence:pack}:{})});setError('');}}>Применить цену</button>{value&&<button type="button" onClick={()=>onSave(undefined)}>Убрать цену из расчёта</button>}{error&&<p role="alert">{error}</p>}{value&&<p className="hint">Внесено {new Date(value.observedAt).toLocaleString('ru-RU')} · <a href={value.sourceUrl} target="_blank" rel="noopener noreferrer">{value.description}</a>{value.packageEvidence&&<> · {value.packageEvidence.operatorName}, {value.packageEvidence.operatorCountry} · {value.packageEvidence.hotel}, {value.packageEvidence.room}, {value.packageEvidence.meal}</>}</p>}</details>;
}
