'use client';
import {useEffect,useState} from 'react';
import {Database,ExternalLink,Info,LoaderCircle} from 'lucide-react';
import PublicPrices from './PublicPrices';
import {defaults,defaultParty,type Filters,type Party} from '@/lib/search';
import {apiAvailable,apiBaseUrl} from '@/lib/api';
type Source={provider:string;access_status:string;pricing_reality:string;bookable:boolean|null;note:string;source_url:string};
const api=apiBaseUrl;
export default function Sources({filters=defaults,party=defaultParty}:{filters?:Filters;party?:Party}){
 const [sources,setSources]=useState<Source[]>([]),[status,setStatus]=useState(''),[test,setTest]=useState<null|Record<string,unknown>>(null),[busy,setBusy]=useState(false);
 async function check(){if(!apiAvailable){setStatus('На GitHub Pages доступен архив открытых цен. Серверный API не подключён; проверки поставщиков здесь недоступны.');return;}try{const r=await fetch(api+'/api/providers',{signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error();const d=await r.json();setSources(d.providers);setStatus(d.message)}catch{setStatus('Backend недоступен. Запустите его по инструкции README.md. Локальная демонстрация продолжает работать.')}}
 useEffect(()=>{check()},[]);
 async function probe(path:string){if(!apiAvailable)return;setBusy(true);setTest(null);try{const r=await fetch(api+path,{signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(`HTTP ${r.status}`);setTest(await r.json())}catch(e){setTest({error:'Источник недоступен. Реальные цены не подставлены.',detail:String(e)})}setBusy(false)}
 return <section className="sources"><div className="results-top"><div><div className="eyebrow">DEMO-FIRST · ПРОВЕРЕНО 19.09.2026</div><h2>Источники и происхождение цен</h2></div><button className="primary" disabled={!apiAvailable} onClick={check}>Обновить статусы</button></div><div className="notice"><Info size={20}/><p>{status||'Проверяем доступ к серверу…'}</p></div><div className="sandbox-actions"><button className="primary" disabled={busy||!apiAvailable} onClick={()=>probe('/api/sandbox/travelgate')}>Проверить HOTELTEST</button><button className="primary" disabled={busy||!apiAvailable} onClick={()=>probe('/api/sandbox/dida-content')}>Справочник Dida</button><button className="primary" disabled={busy||!apiAvailable} onClick={()=>probe('/api/weather?latitude=27&longitude=33.9')}>Прогноз Open-Meteo</button></div>{busy&&<p className="loading"><LoaderCircle className="spin" size={18}/> Запрос только на чтение…</p>}{test&&<div className="probe-result"><h3>Ответ источника</h3>{Boolean(test.pricing_reality)&&<p>Цены: <strong>{String(test.pricing_reality)}</strong> · Бронирование: <strong>{test.bookable===false?'нет':'не подтверждено'}</strong></p>}{test.fallback===true&&<p>Сработал MOCK fallback: upstream demo не вернул пригодные тарифы.</p>}{Array.isArray(test.offers)&&<div className="sandbox-offers">{(test.offers as {id:string;hotel?:{name:string};price:{original_amount:string;original_currency:string};meal?:string}[]).slice(0,6).map((o,i)=><div key={o.id||i}><span>{o.hotel?.name||'Тестовый отель'}</span><strong>{o.price.original_amount} {o.price.original_currency}</strong><small>Тестовый тариф · не для покупки</small></div>)}</div>}<details><summary>Посмотреть данные ответа</summary><pre>{JSON.stringify(test,null,2)}</pre></details></div>}<div className="source-grid">{sources.map(s=><article key={s.provider}><Database size={23}/><h3>{s.provider}</h3><dl><div><dt>Доступ</dt><dd>{s.access_status}</dd></div><div><dt>Цены</dt><dd>{s.pricing_reality}</dd></div><div><dt>Можно купить</dt><dd>{s.bookable===true?'Да':s.bookable===false?'Нет':'Не подтверждено'}</dd></div></dl><p>{s.note}</p>{s.source_url.startsWith('https://')&&<a href={s.source_url} target="_blank" rel="noreferrer">Официальная документация <ExternalLink size={15}/></a>}</article>)}</div><PublicPrices filters={filters} party={party}/><div className="weather-live"><h3>Техническая проверка ≠ доказанная экономия</h3><p>SANDBOX, DEMO, EVALUATION и MOCK не участвуют в сравнении с реальными пакетами. В рабочем режиме нет ни одного подтверждённого реального тарифа. Частичный справочник стран также не подтверждает доступ к ценам.</p><small>Прогноз: <a href="https://open-meteo.com/">Open-Meteo</a> · CC BY 4.0. Исторический климат и прогноз хранятся раздельно.</small></div></section>
}
