'use client';
import {useState,useEffect,useMemo,useRef,useCallback} from 'react';
import Sources from '@/components/Sources';
import PublicPrices from '@/components/PublicPrices';
import ProviderSearch from '@/components/ProviderSearch';
import SearchSources from '@/components/SearchSources';
import PurchaseDetails from '@/components/PurchaseDetails';
import {calculationSummary,calculationValid,tripStorageKey,type TripCalculation} from '@/lib/trip-quotes';
import LiveOffers,{type LiveSearchResponse} from '@/components/LiveOffers';
import {apiAvailable,apiBaseUrl,staticDeploy} from '@/lib/api';
import {Globe2,Search,SlidersHorizontal,ArrowUpRight,ArrowRight,Plane,ShieldCheck,Users,CalendarDays,Waves,Sun,Heart,GitCompareArrows,X,ChevronDown,MapPin,Info,Compass,TriangleAlert,RotateCcw,Plus,Minus,LoaderCircle} from 'lucide-react';
import {addDays,countryOptions,selectedCountryCodes,defaults,defaultParty,defaultSearchSourceSettings,sections,searchMock,money,shortDate,kindLabels,type Filters,type Party,type Offer,type Field,type SearchSourceSettings} from '@/lib/search';

const tabs=[['all','ВСЕ'],['tourOperators','ТУРОПЕРАТОРЫ'],['foreignOperators','ЗАРУБЕЖНЫЕ ТУРОПЕРАТОРЫ'],['wholesalers','ОПТОВИКИ / B2B'],['retail','САМОСТОЯТЕЛЬНО'],['charters','ЧАРТЕРЫ']];
const api=apiBaseUrl;
function freshDefaultFilters():Filters {
 const tomorrow=addDays(new Date().toLocaleDateString('sv-SE'),1);
 if(String(defaults.latestDeparture)<=tomorrow)return {...defaults,earliest:tomorrow,latestDeparture:addDays(tomorrow,45),latest:addDays(tomorrow,65)};
 return {...defaults,earliest:tomorrow};
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null),closeRef=useRef(close);
 useEffect(()=>{closeRef.current=close},[close]);
 useEffect(()=>{const d=ref.current;d?.showModal();const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current()};document.addEventListener('keydown',fn);return()=>{document.removeEventListener('keydown',fn);d?.close()}},[]);
 return <dialog ref={ref} className="dialog" onCancel={close}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Закрыть"><X size={22}/></button></header>{children}</dialog>;
}
function Input({field,f,set}:{field:Field;f:Filters;set:(k:string,v:string|number|boolean)=>void}){
 const id='filter-'+field.key;
 if(field.type==='check')return <label className="check-field" htmlFor={id}><input id={id} type="checkbox" checked={Boolean(f[field.key])} onChange={e=>set(field.key,e.target.checked)}/><span>{field.label}</span></label>;
 return <label className="field" htmlFor={id}><span>{field.label}</span>{field.type==='select'?<select id={id} value={String(f[field.key])} onChange={e=>set(field.key,e.target.value)}>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:<input id={id} type={field.type} min={field.min} max={field.max} step={field.key==='rating'||['water','colour','clarity'].includes(field.key)?'.1':'1'} value={String(f[field.key])} onChange={e=>set(field.key,field.type==='number'?Number(e.target.value):e.target.value)}/>}</label>;
}
export default function Home(){
 const [f,setF]=useState<Filters>(defaults),[party,setParty]=useState<Party>(defaultParty),[sourceSettings,setSourceSettings]=useState<SearchSourceSettings>(defaultSearchSourceSettings),[tab,setTab]=useState('all'),[mode,setMode]=useState('live'),[view,setView]=useState('search');
 const [detail,setDetail]=useState<Offer|null>(null),[booking,setBooking]=useState<Offer|null>(null),[compare,setCompare]=useState<Offer[]>([]),[showCompare,setShowCompare]=useState(false),[saved,setSaved]=useState<Offer[]>([]),[loaded,setLoaded]=useState(false);
 const [calculations,setCalculations]=useState<Record<string,TripCalculation>>({});
 const updateCalculation=useCallback((c:TripCalculation)=>{if(calculationValid(c))setCalculations(prev=>JSON.stringify(prev[c.offerKey])===JSON.stringify(c)?prev:{...prev,[c.offerKey]:c})},[]);
 const calculationFor=useCallback((o:Offer)=>calculations[tripStorageKey(o,party,f)],[calculations,party,f]);
 const priceFor=useCallback((o:Offer)=>calculationSummary(calculationFor(o)),[calculationFor]);
 const priceText=(o:Offer)=>{const p=priceFor(o);return p.known?money(p.total):'Цена не найдена';};
 const [validationTrigger,setValidationTrigger]=useState(0);
 const [busy,setBusy]=useState(false),[live,setLive]=useState<LiveSearchResponse|null>(null),[filtersOpen,setFiltersOpen]=useState(false),[toast,setToast]=useState('');
 const searchSequence=useRef(0),searchAbort=useRef<AbortController|null>(null);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('gto-saved-v1')||'[]');if(Array.isArray(s))setSaved(s.filter(x=>x&&typeof x.id==='string'&&x.demo===true))}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem('gto-saved-v1',JSON.stringify(saved))},[saved,loaded]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)}},[toast]);
 const set=(key:string,value:string|number|boolean)=>setF(prev=>({...prev,[key]:value}));
 const setTripDate=(key:'earliest'|'latest',value:string)=>setF(prev=>key==='earliest'?{...prev,earliest:value,latestDeparture:String(prev.latestDeparture)<value?value:prev.latestDeparture,latest:String(prev.latest)<value?value:prev.latest}:{...prev,latest:value,latestDeparture:String(prev.latestDeparture)>value?value:prev.latestDeparture});
 const toggleCountry=(code:string)=>setF(prev=>{const selected=new Set(selectedCountryCodes({...prev,destinationMode:'Выбранные страны'}));if(selected.has(code))selected.delete(code);else selected.add(code);return {...prev,destinations:[...selected].join(',')};});
 useEffect(()=>{setF(freshDefaultFilters())},[]);
 const data=useMemo(()=>searchMock(f,party,sourceSettings),[f,party,sourceSettings]);
 useEffect(()=>{searchSequence.current++;searchAbort.current?.abort();searchAbort.current=null;setBusy(false);setLive(null)},[f,party,sourceSettings,mode]);
 useEffect(()=>()=>searchAbort.current?.abort(),[]);
 const displayed=useMemo(()=>{const os=view==='saved'?[...saved]:[...data.offers];const matches=(o:Offer)=>tab==='all'||tab==='tourOperators'&&['russian','foreign','gatewayPackage'].includes(o.kind)||tab==='foreignOperators'&&['foreign','gatewayPackage'].includes(o.kind)||tab==='wholesalers'&&o.kind==='wholesale'||tab==='retail'&&o.kind==='diy'||tab==='charters'&&o.kind==='charter';return os.filter(matches).sort((a,b)=>{const x=priceFor(a),y=priceFor(b);return Number(y.complete)-Number(x.complete)||(x.complete&&y.complete?x.total-y.total:0)||Number(y.known>0)-Number(x.known>0)||b.score-a.score}).slice(0,20)},[data,tab,view,saved,priceFor]);
 useEffect(()=>{const found:Record<string,TripCalculation>={};for(const o of [...data.offers,...saved]){const k=tripStorageKey(o,party,f);try{const c=JSON.parse(localStorage.getItem(k+':calculation')||'null');if(calculationValid(c)&&c.offerKey===k)found[k]=c;}catch{}}setCalculations(prev=>{const next={...prev,...found};return JSON.stringify(next)===JSON.stringify(prev)?prev:next});},[data,saved,party,f]);
 const toggleSave=(o:Offer)=>{setSaved(prev=>prev.some(s=>s.id===o.id)?prev.filter(s=>s.id!==o.id):[...prev,o]);};
 const toggleCompare=(o:Offer)=>{if(compare.some(c=>c.id===o.id))setCompare(compare.filter(c=>c.id!==o.id));else if(compare.length<4)setCompare([...compare,o]);else setToast('Можно сравнить до четырёх вариантов')};
 async function runSearch(){
  if(data.errors.length){setToast(data.errors[0]);document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
  if(mode==='validation'){setValidationTrigger(v=>v+1);return;}
  searchAbort.current?.abort();
  const requestId=++searchSequence.current,controller=new AbortController();searchAbort.current=controller;
  setBusy(true);
  try{if(mode==='live'){
   if(!apiAvailable){setLive({message:'GitHub Pages показывает сохранённые открытые цены. Для новой проверки источников нужен отдельно размещённый API.'});return;}
   const tomorrow=addDays(new Date().toLocaleDateString('sv-SE'),1);
   const earliest=String(f.earliest)>tomorrow?String(f.earliest):tomorrow;
   const lastPossible=addDays(String(f.latest),-Number(f.minNights));
   const latestDeparture=String(f.latestDeparture)<lastPossible?String(f.latestDeparture):lastPossible;
   if(earliest>latestDeparture){setLive({message:'В выбранном окне уже нет будущей даты вылета с указанным количеством ночей. Измените даты поездки.'});return;}
   const r=await fetch(api+'/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filters:{...f,earliest,latestDeparture},party,source_settings:sourceSettings}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(45000)])});
   if(!r.ok)throw new Error(`HTTP ${r.status}`);
   const result=await r.json();if(requestId===searchSequence.current)setLive(result);
  }else await new Promise(r=>setTimeout(r,300));}
  catch(e){if(requestId===searchSequence.current&&!controller.signal.aborted)setLive({message:`Сервер поиска недоступен: ${String(e)}. Цены не подставлены.`})}
  finally{if(requestId===searchSequence.current){searchAbort.current=null;setBusy(false);document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'})}}
 }
 return <>
  <header className="topbar"><a className="brand" href={(process.env.NEXT_PUBLIC_SITE_BASE_PATH||'')+'/'} aria-label="Global Travel Optimizer"><span className="brandmark"><Compass size={26}/></span><span>GLOBAL TRAVEL<span className="brand-sub">OPTIMIZER</span></span></a><nav aria-label="Основная навигация"><button className={view==='search'?'nav active':'nav'} onClick={()=>setView('search')}>Поиск поездки</button><button className={view==='saved'?'nav active':'nav'} onClick={()=>setView('saved')}>Сохранённое <span className="count">{saved.length}</span></button><button className={view==='sources'?'nav active':'nav'} onClick={()=>setView('sources')}>Источники</button></nav><div className="top-meta"><span>RUB · Русский</span><span className="avatar">Д</span></div></header>
  <main>
   <div className="page-heading"><div><div className="eyebrow">МЕНЬШЕ ОГРАНИЧЕНИЙ. БОЛЬШЕ ВОЗМОЖНОСТЕЙ.</div><h1>Ваш отдых. Все варианты.</h1><p>Сравните тур, свою сборку и вылет из другой страны — по полной стоимости.</p></div><span className="read-only"><ShieldCheck size={17}/> Только поиск, без бронирования</span></div>
   {view==='sources'?<Sources filters={f} party={party}/>:<>
   <section className="search-panel" aria-label="Параметры поездки"><div className="search-fields"><label><span><MapPin size={16}/> Откуда</span><input aria-label="Город вылета" value={String(f.origin)} onChange={e=>set('origin',e.target.value)}/><small>{String(f.airports).replaceAll(',',' · ')}</small></label><label><span><Globe2 size={16}/> Куда</span><select aria-label="Выбор направления" value={String(f.destinationMode)} onChange={e=>set('destinationMode',e.target.value)}><option>Любой пляж</option><option>Выбранные страны</option></select><small>Направление подберём по требованиям</small></label><label><span><CalendarDays size={16}/> Окно поездки</span><div className="date-pair"><input aria-label="Начало окна" type="date" value={String(f.earliest)} onChange={e=>setTripDate('earliest',e.target.value)}/><input aria-label="Конец окна" type="date" value={String(f.latest)} onChange={e=>setTripDate('latest',e.target.value)}/></div><small>{String(f.minNights)}–{String(f.maxNights)} ночей · гибкие даты</small></label><button className="party-shortcut" onClick={()=>{setFiltersOpen(true);document.getElementById('travellers')?.scrollIntoView({behavior:'smooth'})}}><span><Users size={16}/> Кто едет</span><strong>{party.adults} взрослых · {party.children.length} детей</strong><small>{party.split?'Разные даты возвращения':party.children.map(a=>a+' лет').join(', ')}</small></button><button className="search-button" onClick={runSearch} disabled={busy}>{busy?<LoaderCircle className="spin" size={20}/>:<Search size={20}/>} Найти отдых</button></div>{f.destinationMode==='Выбранные страны'&&<fieldset className="country-picker"><legend>Выберите страны для поиска</legend><div>{countryOptions.map(({code,name})=><button type="button" key={code} aria-pressed={selectedCountryCodes(f).includes(code)} className={selectedCountryCodes(f).includes(code)?'selected':''} onClick={()=>toggleCountry(code)}>{name}</button>)}</div><small>Показываются только выбранные страны. Если опубликованных цен по ним нет, выдача останется пустой.</small></fieldset>}<div className="visa-bar"><label><input type="checkbox" checked={Boolean(f.schengen)} onChange={e=>set('schengen',e.target.checked)}/> У меня есть действующая Шенгенская виза</label><span><ShieldCheck size={15}/>{f.schengen?'Условия въезда всё равно требуют проверки':'Маршруты, требующие въезда в Шенген, автоматически исключаются'}</span></div></section>
   <SearchSources value={sourceSettings} onChange={setSourceSettings}/>
   <div className="workspace"><aside className={filtersOpen?'filters mobile-open':'filters'}><div className="filter-title"><h2><SlidersHorizontal size={18}/> Ваши условия</h2><button title="Сбросить фильтры" aria-label="Сбросить фильтры" onClick={()=>{setF(freshDefaultFilters());setParty(defaultParty);setSourceSettings(defaultSearchSourceSettings)}}><RotateCcw size={16}/></button></div><div className="budget-box"><label htmlFor="budget">Бюджет всей поездки</label><strong>{money(Number(f.budget))}</strong><input id="budget" type="range" min="150000" max="1500000" step="10000" value={Number(f.budget)} onChange={e=>set('budget',Number(e.target.value))}/><div><span>150 тыс.</span><span>1,5 млн ₽</span></div></div>
    <details id="travellers"><summary>Путешественники <span>{party.adults+party.children.length}</span></summary><div className="details-body"><label className="field"><span>Взрослых</span><input type="number" min="1" max="8" value={party.adults} onChange={e=>setParty({...party,adults:Number(e.target.value)})}/></label><p className="muted">Возраст каждого ребёнка</p><div className="child-list">{party.children.map((a,i)=><div key={i}><input aria-label={`Возраст ребёнка ${i+1}`} type="number" min="0" max="17" value={a} onChange={e=>setParty({...party,children:party.children.map((v,j)=>j===i?Number(e.target.value):v)})}/><button aria-label={`Убрать ребёнка ${i+1}`} onClick={()=>setParty({...party,children:party.children.filter((_,j)=>i!==j),split:false})}><Minus size={14}/></button></div>)}</div><button className="text-button" disabled={party.children.length>=8} onClick={()=>setParty({...party,children:[...party.children,5],split:false})}><Plus size={15}/> Добавить ребёнка</button><label className="check-field"><input type="checkbox" checked={party.split} onChange={e=>setParty({...party,split:e.target.checked})}/>Возвращаться в разные даты</label>{party.split&&party.groups.map((g,i)=><div className="group" key={g.name}><strong>{g.name}</strong><label className="field"><span>Взрослых в группе</span><input type="number" min="1" max="8" value={g.adults} onChange={e=>setParty({...party,groups:party.groups.map((v,j)=>j===i?{...v,adults:Number(e.target.value)}:v)})}/></label><div className="two-fields">{(['minNights','maxNights'] as const).map(k=><label className="field" key={k}><span>{k==='minNights'?'Ночей от':'Ночей до'}</span><input type="number" min="1" max="60" value={g[k]} onChange={e=>setParty({...party,groups:party.groups.map((v,j)=>j===i?{...v,[k]:Number(e.target.value)}:v)})}/></label>)}</div>{party.children.map((age,j)=><label className="check-field" key={j}><input type="checkbox" checked={g.children.includes(j)} onChange={e=>setParty({...party,groups:party.groups.map((v,k)=>k===i?{...v,children:e.target.checked?[...v.children,j]:v.children.filter(x=>x!==j)}:{...v,children:e.target.checked?v.children.filter(x=>x!==j):v.children})})}/>Ребёнок {j+1} · {age} лет</label>)}</div>)}{party.split&&<p className="hint">Вылет общий. Проживание, трансферы и обратный путь рассчитываются для каждой группы.</p>}</div></details>
    {sections.map(section=><details key={section.name}><summary>{section.name}<ChevronDown size={15}/></summary><div className="details-body">{section.fields.map(field=><Input key={field.key} field={field} f={f} set={set}/>)}{section.name==='Документы и визы'&&<p className="hint">Визы других стран не считаются разрешением на въезд без проверки правил. Airside разрешается только по актуальному подтверждению конкретной пересадки.</p>}</div></details>)}
    <div className="sidebar-note"><ShieldCheck size={20}/><p>Цена для всей семьи.<br/>С багажом, трансферами и обязательными расходами.</p></div><button className="mobile-done" onClick={()=>setFiltersOpen(false)}>Показать варианты</button></aside>
    <section className="results" id="results"><div className="results-top"><div><div className="eyebrow">OPPORTUNITY SCANNER</div><h2>{view==='saved'?'Сохранённые варианты':'Куда отправимся в путешествие?'}</h2></div><div className="mode-switch" aria-label="Режим данных"><button className={mode==='demo'?'selected':''} onClick={()=>setMode('demo')}>Демо</button><button className={mode==='live'?'selected':''} onClick={()=>{setMode('live');setLive(null)}}>Реальный поиск</button><button className={mode==='validation'?'selected':''} onClick={()=>setMode('validation')}>API тест</button></div></div>
    <div className="notice"><Info size={19}/><div><strong>{mode==='demo'?'Демонстрация возможностей':mode==='validation'?'Проверка интеграций без покупки API':staticDeploy&&!apiAvailable?'Архив открытых цен':'Открытые цены и статус поиска'}</strong><p>{mode==='validation'?'Sandbox, demo и mock не участвуют в выводах об экономии.':mode==='demo'?'Карточки показывают учебные суммы с меткой SYNTHETIC. Цены продавцов показываются отдельно по внесённым источникам. Учебные суммы не доказывают экономию или наличие мест.':'Ниже показаны цены, действительно увиденные на публичных страницах, со временем наблюдения и ссылкой. Это отдельные расходы, пока не полная стоимость семейной поездки. Подключённые sandbox источники показаны отдельно.'}</p></div></div>
    <button className="mobile-filter" onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={17}/> Настроить фильтры</button>
    {data.errors.length>0&&<div role="alert" className="error-box">{data.errors.map(e=><p key={e}>{e}</p>)}</div>}
    {mode==='demo'?<><div className="summary-row"><div><span>Сценариев проверено</span><strong>{data.scenarios.toLocaleString('ru-RU')}</strong></div><div><span>Подходящих моделей</span><strong>{data.offers.length}</strong></div><div><span>Учебная сумма от · SYNTHETIC</span><strong>{data.offers.length?money(Math.min(...data.offers.map(o=>o.price))):'Не определена'}</strong></div></div><div className="tabs" role="tablist" aria-label="Сортировка и тип отдыха">{tabs.map(([key,title])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'tab selected':'tab'} onClick={()=>setTab(key)}>{title}</button>)}</div><div className="result-caption"><span>{view==='saved'?saved.length:data.offers.length} вариантов · показано {displayed.length}</span><span>Для {party.adults+party.children.length} путешественников</span></div>
    <div className="cards">{displayed.map(o=><article className="offer" key={o.id}><div className={`destination-art art-${o.code.toLowerCase()}`}><div className="art-top"><span>{kindLabels[o.kind]}</span><button aria-label={saved.some(s=>s.id===o.id)?'Удалить из сохранённого':'Сохранить вариант'} onClick={()=>toggleSave(o)}><Heart size={18} fill={saved.some(s=>s.id===o.id)?'currentColor':'none'}/></button></div><div className="destination-type">{o.code} / BEACH ESCAPE</div><h3>{o.resort}</h3><p>{o.country}</p><div className="art-bottom"><span><Waves size={16}/> {o.sea}° море</span><span><Sun size={16}/> {o.air}° воздух</span></div></div><div className="offer-main"><div className="offer-heading"><span className="hotel-stars">{'★'.repeat(o.stars)} <span>{o.rating.toFixed(1)} / 10</span></span><span className="demo-tag">ДЕМО</span></div><h3>{o.hotel}</h3><p className="offer-date"><CalendarDays size={15}/>{shortDate(calculationFor(o)?.departure||o.departure)} — {(calculationFor(o)?.returns||o.returns).map(shortDate).join(' / ')}<b>{calculationFor(o)?'Даты расчёта':o.nights.join(' / ')+' ночей'}</b></p><div className="chips"><span>{o.meal==='AI'?'Всё включено':o.meal==='BB'?'Завтраки':o.meal}</span><span>Первая линия</span><span>Багаж: проверить тариф</span></div><div className="route"><Plane size={16}/>{calculationFor(o)?calculationFor(o)!.from+' → '+calculationFor(o)!.to:o.route.join(' → ')}</div>{o.gateway&&<div className="foreign-package-summary"><span><b>{o.operatorName}</b> · {o.operatorCountry}</span><span>Старт: {o.startAirport}</span><span>Цена дороги: по источникам в деталях</span><span>Ночёвка: {o.overnightNeeded?'да':'нет'}</span><span>Self-transfer: {o.selfTransfer?'да':'нет'}</span><span>Виза: {o.visaDecision}</span></div>}<div className="scores"><span><Waves size={15}/> Вода <b>{o.water}/5</b></span><span><Sun size={15}/> Погода <b>{o.weather}</b></span><span><Users size={15}/> Семья <b>{o.family}</b></span></div><div className="visa-status"><TriangleAlert size={14}/> Виза и наличие требуют проверки</div></div><div className="offer-price"><div className="match"><span>{o.score}</span><div>соответствие<br/>из 100</div></div><div className="price-block"><small>{priceFor(o).known?(priceFor(o).complete?'Полная стоимость по источникам':'Найденные составляющие'):'Учебная модель · SYNTHETIC'} · {o.people} человек</small><strong>{priceFor(o).known?priceText(o):money(o.price)}</strong><span>{priceFor(o).complete?'По внесённым источникам':priceFor(o).known?'Полная стоимость не определена':'Не цена продавца · наличие не подтверждено'}</span>{priceFor(o).known>0&&<span className="model-only">Учебная модель: {money(o.price)} · SYNTHETIC</span>}</div><button className="details-button" onClick={()=>setDetail(o)}>Подробнее <ArrowUpRight size={17}/></button><label className="compare-check"><input type="checkbox" checked={compare.some(c=>c.id===o.id)} onChange={()=>toggleCompare(o)}/> Сравнить</label></div></article>)}</div>
    {displayed.length===0&&<div className="empty"><Compass size={38}/><h3>Подходящих вариантов пока нет</h3><p>{view==='saved'?'Сохраните интересный вариант кнопкой с сердцем.':'Попробуйте увеличить бюджет или смягчить условия. Локальные модели поддерживают вылет из Москвы и обычный паспорт РФ; реальные правила не подменяются догадками.'}</p><button onClick={()=>{setF(defaults);setParty(defaultParty);setSourceSettings(defaultSearchSourceSettings);setTab('all')}}>Сбросить фильтры</button></div>}
    </>:mode==='validation'?<ProviderSearch filters={f} party={party} trigger={validationTrigger}/>:<><PublicPrices filters={f} party={party} showPackages={sourceSettings.search_tour_operators&&(sourceSettings.search_russian_operators||sourceSettings.search_foreign_operators)}/><LiveOffers filters={f} offers={live?.offers||[]} attempted={live?.attempted||[]} providers={live?.providers||[]} message={live?.message||(staticDeploy&&!apiAvailable?'GitHub Pages показывает сохранённые открытые цены. Для новых запросов нужен отдельный API.':null)} apiAvailable={apiAvailable} busy={busy} onSearch={runSearch}/></>}
    <footer className="results-footer"><ShieldCheck size={16}/><span>Никаких автоматических покупок. Бронирование и оплата — только у поставщика.</span></footer></section></div></>}
  </main>
  {compare.length>0&&<div className="compare-dock"><GitCompareArrows size={20}/><span>Выбрано {compare.length} из 4</span><button onClick={()=>setShowCompare(true)}>Сравнить варианты <ArrowRight size={16}/></button><button className="icon-button" aria-label="Очистить сравнение" onClick={()=>setCompare([])}><X size={18}/></button></div>}
  {toast&&<div role="status" className="toast">{toast}</div>}
  {detail&&<Modal title={detail.resort+' · детали поездки'} close={()=>setDetail(null)}><div className="modal-body"><div className="notice"><Info size={18}/><p>Сценарий: MOCK · SYNTHETIC · bookable: false. Отель и оценки учебные. Цены из внешних источников учитываются отдельно в расчёте ниже. Наличие мест не подтверждено.</p></div><h3>Маршрут и возвращение</h3><div className="route-detail">{detail.route.map((r,i)=><span key={i}>{r}{i<detail.route.length-1&&<ArrowRight size={16}/>}</span>)}</div>{detail.returns.map((r,i)=><div className="split-line" key={i}><Users size={18}/><span>{detail.groupLabels[i]}</span><strong>{shortDate(calculationFor(detail)?.departure||detail.departure)} → {shortDate(calculationFor(detail)?.returns[i]||r)} · даты запроса</strong></div>)}<PurchaseDetails key={tripStorageKey(detail,party,f)} offer={detail} party={party} filters={f} onCalculation={updateCalculation}/>{detail.gateway&&<details><summary>Учебная модель зарубежного маршрута</summary><div className="foreign-detail"><div><span>Туроператор</span><b>{detail.operatorName} · {detail.operatorCountry}</b></div><div><span>Аэропорт старта тура</span><b>{detail.startAirport}</b></div><div><span>Доступ из России</span><b>{detail.route.join(' → ')}</b></div><div><span>Позиционирование</span><b>{money(detail.positioningCost)}</b></div><div><span>Ночёвка</span><b>{detail.overnightNeeded?`Да · ${money(detail.gatewayHotelCost)}`:'Нет'}</b></div><div><span>Self-transfer</span><b>{detail.selfTransfer?'Да':'Нет'}</b></div><div><span>Виза</span><b>{detail.visaDecision}</b></div><div><span>Цена пакета</span><b>{money(detail.packagePrice)}</b></div><div><span>Доп. расходы</span><b>{money(detail.additionalCosts)}</b></div><div className="total-real"><span>Синтетическая модель</span><b>{money(detail.totalRealCost)}</b></div></div></details>}
<h3>Почему этот вариант</h3><p>{detail.explanation}</p><div className="risk-grid"><div><span>Риск пересадки</span><strong>{detail.risk}/100</strong><small>{detail.gateway?`Запас ${detail.buffer} ч; отдельные билеты`:'Модель единого перелёта'}</small></div><div><span>Риск покупки</span><strong>{detail.bookingRisk}/100 · HIGH</strong><small>Продавец, оплата и гражданство не подтверждены</small></div></div><h3>Погода и пляж</h3><p>Климатическая модель: {detail.weather}/100. Реальный прогноз: отсутствует. Доверие: низкое — демонстрация. Оценка воды: {detail.water}/5; пляжа: {detail.beach}/100.</p><h3>Проверка перед покупкой</h3><p>Нужны актуализация цены и мест, правила въезда на каждый участок, размещение детей, условия отмены, допустимость паспорта и способа оплаты. Никакой реальный поставщик не подтвердил эту модель.</p><button className="primary" onClick={()=>{setBooking(detail);setDetail(null)}}>Как проверить и забронировать <ArrowUpRight size={17}/></button></div></Modal>}
  {booking&&<Modal title="Как проверить поездку" close={()=>setBooking(null)}><div className="modal-body"><PurchaseDetails key={tripStorageKey(booking,party,f)} offer={booking} party={party} filters={f} onCalculation={updateCalculation}/><ol><li>Подключите согласованный API поставщика в разделе «Источники».</li><li>Проверьте паспортные, визовые и транзитные требования для каждого участника.</li><li>Получите подтверждение цены, багажа, размещения детей и условий оплаты.</li><li>Бронируйте только после повторной проверки всех частей поездки.</li></ol><button className="primary" onClick={()=>{setBooking(null);setView('sources')}}>Открыть источники <ArrowRight size={17}/></button></div></Modal>}
  {showCompare&&<Modal title="Сравнение полной стоимости" close={()=>setShowCompare(false)}><div className="modal-body"><p className="hint">Суммы источников и учебная модель показаны отдельными строками. Синтетическая цена не участвует в выводах об экономии; реальные неполные суммы тоже нельзя сравнивать как полную стоимость.</p><div className="table-scroll"><table><thead><tr><th>Параметр</th>{compare.map(o=><th key={o.id}>{o.resort}<small>{kindLabels[o.kind]}</small></th>)}</tr></thead><tbody>{[['Найденные составляющие',(o:Offer)=>priceText(o)],['Полнота стоимости',(o:Offer)=>priceFor(o).complete?'Все строки заполнены':'Не определена'],['Учебная модель · SYNTHETIC',(o:Offer)=>money(o.price)],['Даты',(o:Offer)=>`${shortDate(calculationFor(o)?.departure||o.departure)} — ${(calculationFor(o)?.returns||o.returns).map(shortDate).join(' / ')}`],['Ночей',(o:Offer)=>calculationFor(o)?calculationFor(o)!.returns.map(back=>String(Math.round((Date.parse(back)-Date.parse(calculationFor(o)!.departure))/86400000))).join(' / '):o.nights.join(' / ')],['Питание',(o:Offer)=>o.meal],['Gateway',(o:Offer)=>o.gateway||'Нет'],['Погода',(o:Offer)=>o.weather+'/100'],['Вода',(o:Offer)=>o.water+'/5'],['Пересадочный риск',(o:Offer)=>o.risk+'/100'],['Доступность',()=> 'Не подтверждена']].map(([label,fn])=><tr key={String(label)}><th>{String(label)}</th>{compare.map(o=><td key={o.id}>{(fn as (o:Offer)=>string)(o)}</td>)}</tr>)}</tbody></table></div></div></Modal>}
 </>;
}

